name: Deploy to GKE

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2.0.1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Install gke-gcloud-auth-plugin
      run: gcloud components install gke-gcloud-auth-plugin
    
    - name: Authenticate with GCP
      run: |
        echo '${{ secrets.GCP_SA_KEY }}' | gcloud auth activate-service-account --key-file=-
      
    - name: Run script
      run: |
        gcloud container clusters get-credentials ${{ secrets.GKE_CLUSTER_NAME }} --zone ${{ secrets.GKE_CLUSTER_ZONE }}
        chmod +x ./notarobot
        ./notarobot gcp
      env:
        DYNATRACE_ENDPOINT: ${{ secrets.DYNATRACE_ENDPOINT }}
        DYNATRACE_API_TOKEN: ${{ secrets.DYNATRACE_API_TOKEN }}
        GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
        GKE_CLUSTER_NAME: ${{ secrets.GKE_CLUSTER_NAME }}
        GKE_CLUSTER_ZONE: ${{ secrets.GKE_CLUSTER_ZONE }}
